server:
  port: 8082

girl:
  name: liying
  age: 17

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 392485362
    url: jdbc:mysql://localhost:3306/springboot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



